apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-rs
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
     app: login
  template:
      metadata:
        name: login-pod
        labels:
          app: login
      spec:
        containers:
        - name: login-con
          image: sanjaybaskar/webapp-1.0
