apiVersion: v1
kind: Service
metadata:
  name:  sk-service
  labels:
   app: login-app
spec:
  selector:
    app:  login
  type:  NodePort
  ports:
  - nodePort: 31000
    port:  80
    targetPort:  8080